### ISSUE TITLE
Model selection?

### ISSUE THREAD

**Issue by xploz1on** [Loeffeldude/my-chat-gpt#1]
Hi there, first of all let me say, this just works perfect. I was wondering what model is this using by default. GPT 3.5 Turbo, GPT-4?
Would be great to have a option to select the model we want to use. Thank you!

**Comment by Loeffeldude** [comment]
I might Implement this later today. Should be very straight forward.

**Comment by Loeffeldude** [comment]
Oops

**Comment by xploz1on** [comment]
Awesome! Danke! I will update today and test.
