### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by ioanmo226** [Loeffeldude/my-chat-gpt#3]
Hello, Author
I came across your app and I must say, it looks great! I have a few suggestions that might help improve it even more:

- Consider adding more topics or tags to your repository to make it easier for users to discover your app.
- I noticed that the ChatInput UX could use some improvement. Specifically, you could remove the textarea focus outline and set the default behavior to send messages on "Enter" and create a line-break on "Ctrl+Enter". You might also want to consider following the logic used on the official ChatGPT website.
- It would be helpful to include a `Transcribe Audio` button, which would allow users to select audio or mp3 files and transcribe them to text using the Whisper API.

FYI I also created a ChatGPT clone (https://github.com/ioanmo226/chatgpt-web-application). However, after exploring your app, I believe that it has many benefits compared to my clone.

**Comment by winner** [comment]
Hi Nico, I also like you app very much!

Thanks for your effort for building a such nice app.

I look forward to see the next updates for what @ioanmo226  suggested.

Regards.

**Comment by Loeffeldude** [comment]
Hi, 

I don't have a lot of time to work on this  right now. This was more of a weekend project for me to have a cheaper ChatGPT client. I am still actively using it myself and I just wrote a bunch of issues of stuff I would like to see improved.

I'll definitely will improve the Chatinput. it's annoying me too.

Thanks for the suggestion about the tags I'll look into it if I have time. 

I don't know about transcribing audio. It's not a priority for me right now but maybe if I want to try the Whisper API someday. It should be pretty trivial to implement.

I will create new issues of the stuff you mentioned.
